# This is a basic workflow to help you get started with Actions

name: JS Actions

# Controls when the action will run. 
on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          #first-greeting: "Learning Lab User"
          #second-greeting: "New boy"
          third-greeting: "Problem child#"

      - name: ha-ha
        uses: ./.github/actions/joke-action
        if: jokes

      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          joke: ${{steps.jokes.outputs.joke-output}}